
MLX_RED: int = 0xFFFF0000
MLX_GREEN: int = 0xFF00FF00
MLX_BLUE: int = 0xFF0000FF
MLX_WHITE: int = 0xFFFFFFFF
MLX_BLACK: int = 0xFF000000
MLX_YELLOW: int = 0xFFFFFF00
MLX_CYAN: int = 0xFF00FFFF
MLX_PURPLE: int = 0xFF7C6AF7
MLX_ORANGE: int = 0xFFFF8C00

MLX_COLOR_PALETTE: list[int] = [MLX_RED, MLX_BLUE, MLX_WHITE, MLX_YELLOW,
                                MLX_CYAN, MLX_PURPLE, MLX_ORANGE]
